env:
  es2021: true
  jest: true
extends:
  - airbnb-base
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    typescript: {}
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/__tests__/*'
        - '**/__mocks__/*'
        - '**/*.spec.*'
        - '**/*.test.*'
        - '**/*.setup.*'
        - '**/*.config.*'
        - storybook/**/*
        - '**/testUtils/*'
        - '**/types/**'
        - '**/setupTests.*'
  import/order:
    - error
    - pathGroups:
        - pattern: src/**
          group: parent
      groups:
        - builtin
        - external
        - parent
        - sibling
        - index
      newlines-between: always
  import/prefer-default-export: 'off'
  no-use-before-define: 'off'
  '@typescript-eslint/no-use-before-define': error
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
      varsIgnorePattern: '^_'
  no-useless-constructor: 'off'
  '@typescript-eslint/no-useless-constructor':
    - error
  no-shadow: 'off'
  '@typescript-eslint/no-shadow':
    - error
